// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVericationEmail = `-- name: CreateVericationEmail :one
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, updated_at
`

type CreateVericationEmailParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVericationEmail(ctx context.Context, arg CreateVericationEmailParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createVericationEmail, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
